## Deliverable 3. Create a Travel Itinerary Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [5]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Avera,US,77.72,overcast clouds,33.1940,-82.5271,NaN
1,4,Kapaa,US,80.92,light rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
2,8,Rikitea,PF,72.52,clear sky,-23.1203,-134.9692,People ThankYou
3,11,Atuona,PF,77.58,scattered clouds,-9.8000,-139.0333,Villa Enata
4,18,Butaritari,KI,83.12,few clouds,3.0707,172.7902,Isles Sunset Lodge

In [8]:
vacation_clean_df = vacation_df.dropna()
vacation_clean_df.head(10)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,4,Kapaa,US,80.92,light rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
2,8,Rikitea,PF,72.52,clear sky,-23.1203,-134.9692,People ThankYou
3,11,Atuona,PF,77.58,scattered clouds,-9.8000,-139.0333,Villa Enata
4,18,Butaritari,KI,83.12,few clouds,3.0707,172.7902,Isles Sunset Lodge
5,20,Encheng,CN,84.96,light rain,22.1839,112.3026,Pinghu Hostel
6,23,Westport,US,72.75,clear sky,41.1415,-73.3579,The Westport Inn
7,31,Namatanai,PG,81.41,light rain,-3.6667,152.4333,Seagulls Inn Namatani
8,32,Salalah,OM,78.89,broken clouds,17.0151,54.0924,HAMDAN PLAZA HOTEL SALALAH
9,35,Buala,SB,84.04,light rain,-8.1450,159.5921,Maringe Lagoon Lodge
10,37,Saint-Philippe,RE,71.19,scattered clouds,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""

In [9]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current description</dt><dd>{Current Description}</dd>
</dl>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_clean_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_clean_df[["Lat", "Lng"]]

In [10]:
locations = vacation_clean_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [33]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_clean_df.loc[vacation_clean_df['City']== 'Ixtapa']
vacation_end = vacation_clean_df.loc[vacation_clean_df['City']== 'Ixtapa']
vacation_stop1 = vacation_clean_df.loc[vacation_clean_df['City']== 'Guanica']
vacation_stop2 = vacation_clean_df.loc[vacation_clean_df['City']== 'Parrita'] 
vacation_stop3 = vacation_clean_df.loc[vacation_clean_df['City']== 'Cancun']

In [34]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[['Lat','Lng']].to_numpy()
end = vacation_end[['Lat','Lng']].to_numpy()
stop1 = vacation_stop1[['Lat','Lng']].to_numpy()
stop2 = vacation_stop2[['Lat','Lng']].to_numpy()
stop3 = vacation_stop3[['Lat','Lng']].to_numpy()

In [35]:
start = (vacation_start['Lat'].to_list()[0], vacation_start['Lng'].to_list()[0])
end = (vacation_end['Lat'].to_list()[0], vacation_end['Lng'].to_list()[0])
stop1 = (vacation_stop1['Lat'].to_list()[0], vacation_stop1['Lng'].to_list()[0])
stop2 = (vacation_stop2['Lat'].to_list()[0], vacation_stop2['Lng'].to_list()[0])
stop3 = (vacation_stop3['Lat'].to_list()[0], vacation_stop3['Lng'].to_list()[0])

In [36]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
trip_route = gmaps.directions_layer(start,end,waypoints = [stop1,stop2,stop3], travel_mode = 'DRIVING')
fig.add_layer(trip_route)
fig

Figure(layout=FigureLayout(height='420px'))

In [37]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,327,Ixtapa,MX,79.56,overcast clouds,20.7000,-105.2000,Hotel Plaza Providencia
1,632,Guanica,PR,79.25,clear sky,17.9716,-66.9080,Copamarina Beach Resort & Spa
2,329,Parrita,CR,83.97,overcast clouds,9.5201,-84.3225,Beso del Viento
3,99,Cancun,MX,80.51,few clouds,21.1743,-86.8466,Hotel Tankah Cancun

In [38]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [39]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

# 11b. Display the figure

Figure(layout=FigureLayout(height='420px'))